server:
  port: 8081

spring:
  application:
    name: exchange-service
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        types:
          print:
            banner: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

appprops:
  api:
    kraken:
      url: https://api.kraken.com
      pairs: XXBTZUSD,XETHZUSD

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"