server:
  port: 8081
  forward-headers-strategy: native

spring:
  application:
    name: user-management-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    username: demo_admin
    password: demo_admin
    url: jdbc:postgresql://localhost:5432/demo
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: dev
        format_sql: true
        hbm2ddl:
          delimiter: ;
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: none
              create-target: ./user-management-service/target/generated_schema.sql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: dev
    drop-first: true
    enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
