server:
  port: 8081
  forward-headers-strategy: native

spring:
  application:
    name: user-management-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    username: demo_admin
    password: demo_admin
    url: jdbc:postgresql://localhost:5432/demo
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: dev

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
